name: Update CHANGELOG.md
on:
  issue_comment:
    types: [created]  # Add ".changelog" as a PR comment to trigger this workflow.

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: print
        env:
          OWNER: ${{github.repository_owner}}
          BASEREF: ${{github.event.pull_request.base.ref}}
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo OWNER $OWNER
          echo BASEREF $BASEREF
          echo $GITHUB_CONTEXT

  update_changelog:
    runs-on: ubuntu-latest
    # Run if comment is on a PR with the main repo, and if it contains the magic keywords.
    # Or run on PR creation, unless asked otherwise in the title.
    if: |
      github.repository_owner == 'kevinbackhouse' &&
      github.event.issue.pull_request &&
      github.event.pull_request.base.ref == 'dev'

    steps:
      - name: branch-deploy
        id: branch-deploy
        uses: github/branch-deploy@c9fcc362bdcea69eecac6578dde245cd5e3a55bf # v10.4.3
        with:
          trigger: ".changelog"
          reaction: "eyes"
          stable-branch: "dev"

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          token: ${{ secrets.NF_CORE_BOT_AUTH_TOKEN }}

      # Action runs on the issue comment, so we don't get the PR by default.
      # Use the GitHub CLI to check out the PR:
      - name: Checkout Pull Request
        env:
          GH_TOKEN: ${{ secrets.NF_CORE_BOT_AUTH_TOKEN }}
        run: |
          if [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            PR_NUMBER="${{ github.event.issue.number }}"
          elif [[ "${{ github.event_name }}" == "pull_request_target" ]]; then
            PR_NUMBER="${{ github.event.pull_request.number }}"
          fi
          gh pr checkout $PR_NUMBER

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.13"

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Update CHANGELOG.md from the PR title
        env:
          COMMENT: ${{ github.event.comment.body }}
          GH_TOKEN: ${{ secrets.NF_CORE_BOT_AUTH_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number || github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.issue.title || github.event.pull_request.title }}
        run: |
          python ${GITHUB_WORKSPACE}/.github/workflows/changelog.py

      - name: Check if CHANGELOG.md actually changed
        id: file_changed
        run: |
          # Show the diff for debugging
          git diff -- ${GITHUB_WORKSPACE}/CHANGELOG.md

          # Check if file has unstaged changes
          [ -n "$(git diff -- ${GITHUB_WORKSPACE}/CHANGELOG.md)" ] && file_changed="TRUE" || file_changed="FALSE"

          echo "File changed: $file_changed"
          echo "changed=$file_changed" >> $GITHUB_OUTPUT

      - name: Set up Python 3.13
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit checks
        if: steps.file_changed.outputs.changed == 'TRUE'
        run: |
          pre-commit run --all-files

      - name: Commit and push changes
        if: steps.file_changed.outputs.changed == 'TRUE'
        env:
          GH_TOKEN: ${{ secrets.NF_CORE_BOT_AUTH_TOKEN }}
        run: |
          git config user.email "core@nf-co.re"
          git config user.name "nf-core-bot"
          git add ${GITHUB_WORKSPACE}/CHANGELOG.md
          git status
          git commit -m "[automated] Update CHANGELOG.md"
          git push
